### ISSUE TITLE
add prebuilds

### ISSUE THREAD

**Issue by mmckegg** [2bbb/node-abletonlink#4]
Hey @2bbb, thanks for creating this awesome module! I've just incorporated it into my [electron based music software](https://github.com/mmckegg/loop-drop-app), and it is working great!

I'm just wondering if you would be interested in adding prebuild support to this module? https://github.com/mafintosh/prebuildify

This would make packaging my electron app so much simpler as I would no longer have to build on separate machines, and instead could create releases for all platforms from my mac.

I would be happy to do the work of adding prebuilds and sending a pull request! I will also do my best to add a windows prebuild. 

Would you want to merge this PR? If not, I will probably need to fork and make an alternative abletonlink-prebuilt.

**Comment by mmckegg** [comment]
I got this working with [prebuildify](https://github.com/mafintosh/prebuildify): 
https://github.com/mmckegg/node-abletonlink/tree/add-prebuild

But I also found another option: https://github.com/prebuild/prebuild

The difference between [prebuild](https://github.com/prebuild/prebuild) and [prebuildify](https://github.com/mafintosh/prebuildify) is that with `prebuildify`, the binaries for all platforms are included inside the npm tarball, whereas with `prebuild`, they are uploaded to github and downloaded when the user installs the package.

So `prebuildify` makes the install much simpler, but has the tradeoffs of larger download and having to build for all releases before a package can be published.

An advantage to `prebuild` is that it has https://github.com/prebuild/prebuild-ci that lets you use travis-ci to automatically build the releases on all platforms whenever you push a tag. That would make this all very easy. Gonna experiment with this technique and see how it goes.

**Comment by CarloCattano** [comment]
Im interested into this too. Since I can´t figure out how to compile on windows after many trials

**Comment by 2bbb** [comment]
hi @mmckegg !
sorry for late reply.

so, i'm busy while November...

it sounds good. but i want to keep the size small.
i don't know automation with **ify enough.
maybe update frequency of this module is not frequently.
i'm be afraid to make dependencies many and slip into another problem.
i know perhaps this is selfish, i want more simple solution if there is.

but, i'm aware problem about build on windows.
if this toolset clear it and it doesn't break other env, then i will accept this issue.

so, i wrote variously, but anytime i'm waiting PR. because here is github!
feel free to post the PR!

(i promise, in Dec, i will research this again!)

thanks!!

**Comment by 2bbb** [comment]
if you feel this thread is needed, feel free to re-open.
